PRODUCT_VERSION_MAJOR = 2
PRODUCT_VERSION_MINOR = 3
PRODUCT_VERSION_MAINTENANCE = 7

ifdef OXYGEN_NIGHTLY
    PRODUCT_PROPERTY_OVERRIDES += \
        ro.modversion=Oxygen-$(PRODUCT_VERSION_MAJOR)-$(shell date +%d%m%Y)-NIGHTLY-$(PRODUCT_RELEASE_NAME)
else
    ifdef OXYGEN_RELEASE
        PRODUCT_PROPERTY_OVERRIDES += \
            ro.modversion=Oxygen-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)$(PRODUCT_VERSION_DEVICE_SPECIFIC)-$(PRODUCT_RELEASE_NAME)
    else
        PRODUCT_PROPERTY_OVERRIDES += \
            ro.modversion=Oxygen-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)$(PRODUCT_VERSION_DEVICE_SPECIFIC)-$(PRODUCT_RELEASE_NAME)-$(shell date +%d%m%Y)
    endif
endif
